apiVersion: v1
kind: Service
metadata:
  name: my-node-service
spec:
  type: NodePort
  selector:
    app : jawawebapp
  ports:
      
    - port: 80
      targetPort: 80
      
      nodePort: 30007