apiVersion: v1
kind: Pod
metadata:
  name: jawawebapp
  labels:
    app : jawawebapp
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP