apiVersion: v1
kind: ReplicationController
metadata:
  name: kammanireplicationcontroller
spec:
  replicas: 3
  selector:
    app: jawawebapp
  template:
    metadata:
      name: nginx
      labels:
        app: jawawebapp
    spec:
      containers:
      - name: nginxrc
        image: nginx
        ports:
        - containerPort: 80